### PR TITLE
fix manpages with dot

### LINKED ISSUE #13: Can't open mount.cifs manpage
os: centos 7
vscode command input in "Man: Open page" - mount.cifs

expected: open manpage of "mount.cifs" command
received: opened manpage of "mount" command

i think is because command have dot inside write

### PR DESCRIPTION
**Pull request by GitMensch**
Waring, not tested, but I guess that fixes #13

### CODE REVIEW

**Comment by GitMensch** [comment]
Ideally those samples specified are part of some automated test suite...

**Comment by meronz** [comment]
Yes you can add those examples added in the comments as tests. [regex.test.ts](https://github.com/meronz/vscode.manpages/blob/develop/src/test/suite/regex.test.ts) is the place to do it, and you can run tests with `npm run test`.

After doing that, we can merge the PR!
Thanks for that by the way, I'm not having much time on my hands right now so I cannot contribute, but happy to review/merge PRs.

**Comment by meronz** [comment]
I merged another PR that fixes the same problem. I lost track of this and forgot about it. Sorry!

**Comment by GitMensch** [comment]
No problem. Note #19 seems to miss the quite special `[`, in any case it would be good to add the following in the tests:

     // we want to match "getch", "explain_fseek_or_die", "flex++", "["
     
(maybe without the last)

**Pull request closed without merging**
